services:
  web:
    container_name: DANE-TLSA-Bot
    image: ghcr.io/lela810/dane-tlsa-bot:main
    restart: unless-stopped
    environment:
      CFTOKEN:
      CFUID:
      DOMAIN:
      MAILSUBDOMAIN:
      WORKINGMODE: prod / dev
